import '@/styles/globals.css'
import config from '../../app.config'
import { cn } from '@/lib'
import { Inter as FontSans } from 'next/font/google'
import { Header, Footer, PageLayout } from '@/components/global'
import type { Metadata } from 'next'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: `Home | ${config.name}`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <Header />
        <PageLayout>{children}</PageLayout>
        <Footer />
      </body>
    </html>
  )
}
